export const TICKER_MESSAGES: string[] = [
  'BREAKING: SIGINT node reports elevated pressure signatures over US Midwest corridor; analysts cite synchronized lunch windows.',
  'FLASH TRAFFIC: GB metro sensors register a coordinated release wave after pub closing; containment posture remains advisory.',
  'ANALYST BRIEF: DE industrial belt shows recurring 13-minute intervals, suggesting shift-change emissions rather than random noise.',
  'ADVISORY: FR agricultural zones display butter and bean correlation spikes; field teams request expanded culinary metadata.',
  'ASSESSMENT: JP commuter network entered orange status at 08:10 local, with dense carriage clustering as force multiplier.',
  'BREAKING: CN coastal monitors detect broad-spectrum methane bloom near dinner hour; source confidence rated moderate-high.',
  'FLASH TRAFFIC: BR carnival districts exceed seasonal baseline by 240%; command notes rhythm-linked release synchronization.',
  'ANALYST BRIEF: IN corridor data ties chickpea intake to prolonged evening activity; causation review remains in progress.',
  'ADVISORY: AU outback stations report suspicious silence across three sectors; low-activity anomaly now past six hours.',
  'ASSESSMENT: CA western provinces show maple festival uptick, with plume persistence extended by cold-air inversion.',
  'BREAKING: MX urban grid records rapid onset event after street taco surge; medical threat level remains non-critical.',
  'FLASH TRAFFIC: RU northern arrays confirm pressure bursts during rail delays; intent assessed as incidental, not hostile.',
  'ADVISORY: NG coastal hubs register pepper stew correlation exceeding model bounds; analysts recommend temporary recalibration.',
  'ANALYST BRIEF: ZA mining towns exhibit dawn-shift spikes, then abrupt quiet periods flagged as suspicious silence windows.',
  'ASSESSMENT: EG Nile corridor enters caution band after lentil-heavy evening services; persistence expected through midnight.',
  'BREAKING: AR stadium perimeters recorded mass-release event at final whistle; crowd-driven amplification strongly indicated.',
  'FLASH TRAFFIC: KR tech campuses report recurring noon emissions aligned with ramen consumption; confidence level high.',
  'ADVISORY: ID island chain shows weather-assisted drift patterns; monsoon crosswinds extend plume travel beyond forecast.',
  'ANALYST BRIEF: TR transit hubs demonstrate tea-and-bean coupling with elevated output; strategic reserves unaffected.',
  'ASSESSMENT: IT central districts observed post-pasta surge with layered signatures; attribution remains overwhelmingly civilian.',
  'BREAKING: US-CA border sensors log mirrored bursts on both sides; joint task force labels event biologically routine.',
  'FLASH TRAFFIC: GB-FR channel corridor reports intermittent silence pockets; analysts debate sensor masking versus true lull.',
  'ADVISORY: DE and PLUME desk flags pre-storm pressure drops as likely catalyst for tonight\'s regionwide escalation.',
  'ANALYST BRIEF: CN night markets and JP late trains show parallel spikes, supporting shared timing rather than collusion.',
  'ASSESSMENT: BR soybean exports correlate with inland activity climb; economic desk requests integration with freight models.',
  'BREAKING: IN monsoon onset coincides with lower dispersion rates, keeping signatures concentrated over dense metro zones.',
  'FLASH TRAFFIC: AU coastal capitals entered red band at 21:00 local after barbecue peak; advisory remains in effect.',
  'ADVISORY: MX breakfast corridors show egg and salsa trigger cluster; morning watch elevated until 10:30 local time.',
  'ANALYST BRIEF: RU central plains report unusual nighttime quiet; suspicious silence threshold exceeded across four grids.',
  'ASSESSMENT: EG holiday gatherings produced broad urban uptick, though rural stations remain stable and within tolerance.',
  'BREAKING: KR winter inversion traps low-altitude signatures downtown; public guidance upgraded to ventilation priority.',
  'FLASH TRAFFIC: FR diplomatic quarter notes chamber incident during summit lunch; protocol team classifies as accidental.',
  'ADVISORY: IT coastal resorts show gelato-hour calm followed by dinner surge; timing profile now considered seasonal.',
  'ANALYST BRIEF: NG university blocks entered active phase after cafeteria bean stew; student districts lead national index.',
  'ASSESSMENT: ZA weather desk links cold front passage to rapid dissipation, reducing overnight plume persistence risk.',
  'BREAKING: TR and DE freight corridors display synchronized bursts at customs queues; no coordinated intent detected.',
  'FLASH TRAFFIC: JP northern prefectures remain in prolonged silence despite festival traffic; anomaly review escalated.',
  'ADVISORY: AR wheat belt shows modest output rise after empanada fairs; agricultural influence rated plausible.',
  'ANALYST BRIEF: US overnight suburbs indicate steady low-level activity, consistent with baseline domestic comfort patterns.',
  'ASSESSMENT: CN and IN comparative models confirm dinner-hour peaks are predictable, stable, and strategically harmless.',
];
