const now = Date.now()

export const accountSummary = {
  displayName: 'Field Asset Beanstalk',
  identityMode: 'anonymous account linked later to Google',
  sessionAgeDays: 19,
  uploads: 37,
  publicEvents: 31,
  underReview: 3,
  deleted: 3,
  averageRating: 8.3,
}

export const moderationNotes = [
  'Uploader can delete their own events immediately.',
  'Report action stays available to everyone else.',
  'Soft-delete keeps moderation history intact instead of destroying rows.',
  'Google linking upgrades identity without orphaning older uploads.',
]

export const mergeTargets = [
  'server/db.js -> users, event_votes, event_reports, event ownership columns',
  'server/routes.js -> /api/me/events, DELETE /api/events/:id, POST /api/events/:id/report',
  'src/components/HUD -> new profile-facing My Farts panel',
  'src/App.jsx -> swap draft mock data for authenticated API state once accepted',
]

export const reviewChecklist = [
  'Keep the account model: anonymous first, Google optional later.',
  'Decide whether deleted events stay visible in a personal archive or disappear entirely.',
  'Choose whether reported events remain playable while under review.',
  'Confirm if titles and captions belong in v1 or should wait until moderation lands.',
]

export const myEvents = [
  {
    id: 'evt-001',
    title: 'Midnight Rumbler',
    city: 'Chicago',
    countryCode: 'US',
    countryLabel: 'United States',
    createdAt: now - 1000 * 60 * 18,
    status: 'active',
    type: 'epic',
    ratingAverage: 9.1,
    ratingCount: 44,
    hasAudio: true,
    durationSec: 4.8,
    peakDb: -5.2,
    reportCount: 0,
    visibility: 'public',
    caption: 'Recorded after a late bean-heavy dinner. Audio attached, high confidence, zero reports.',
  },
  {
    id: 'evt-002',
    title: 'Transit Corridor Incident',
    city: 'Berlin',
    countryCode: 'DE',
    countryLabel: 'Germany',
    createdAt: now - 1000 * 60 * 60 * 3,
    status: 'review',
    type: 'silent-but-deadly',
    ratingAverage: 7.6,
    ratingCount: 19,
    hasAudio: true,
    durationSec: 7.3,
    peakDb: -12.8,
    reportCount: 2,
    visibility: 'public',
    caption: 'Two users flagged this as possibly fake. Proposed UX keeps it visible but marked under review.',
  },
  {
    id: 'evt-003',
    title: 'Conference Room Echo',
    city: 'Toronto',
    countryCode: 'CA',
    countryLabel: 'Canada',
    createdAt: now - 1000 * 60 * 60 * 11,
    status: 'active',
    type: 'standard',
    ratingAverage: 8.0,
    ratingCount: 13,
    hasAudio: true,
    durationSec: 2.6,
    peakDb: -7.4,
    reportCount: 0,
    visibility: 'public',
    caption: 'Solid community response. This is the kind of upload a self-service dashboard should make easy to revisit or delete.',
  },
  {
    id: 'evt-004',
    title: 'Hotel Lobby Overreach',
    city: 'Tokyo',
    countryCode: 'JP',
    countryLabel: 'Japan',
    createdAt: now - 1000 * 60 * 60 * 27,
    status: 'deleted',
    type: 'standard',
    ratingAverage: 6.4,
    ratingCount: 8,
    hasAudio: true,
    durationSec: 5.1,
    peakDb: -4.1,
    reportCount: 1,
    visibility: 'deleted',
    caption: 'Example of a self-deleted upload that still belongs in an account archive for moderation clarity.',
  },
  {
    id: 'evt-005',
    title: 'Breakfast Shift Change',
    city: 'Sao Paulo',
    countryCode: 'BR',
    countryLabel: 'Brazil',
    createdAt: now - 1000 * 60 * 60 * 43,
    status: 'active',
    type: 'epic',
    ratingAverage: 9.4,
    ratingCount: 51,
    hasAudio: true,
    durationSec: 6.0,
    peakDb: -3.6,
    reportCount: 0,
    visibility: 'public',
    caption: 'A high-performing upload that shows why creator analytics and best-of lists could improve retention.',
  },
]
